[[language]]
name = "java"
file-types = ["java"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
