[[language]]
name = "java"
file-types = ["java"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "html"
file-types = ["html"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true
